apiVersion: v1
kind: ConfigMap
metadata:
  name: obi-config
data:
  obi-config.yml: |
    otel_traces_export:
      endpoint: http://host.minikube.internal:4317
      sampler:
        name: parentbased_traceidratio
        arg: "0.50"
    discovery:
      instrument:
        - k8s_namespace: 'ebpf-poc'
      exclude_instrument:
        - k8s_namespace: 'kube-system'
    attributes:
      select:
        sql_client_duration:
          include: ['*']
