---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beyla
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla
rules:
  # Esto se ocupa para descubrir los pods para instrumentar
  - apiGroups: [""]
    resources:
      - pods
      - services
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch

  # Necesario para leer configuración de deployments
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beyla
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beyla
subjects:
  - kind: ServiceAccount
    name: beyla
    namespace: default  # O tu namespace
